apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-minio
  namespace: argocd
spec:
  destination:
    namespace: gitlab
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://charts.min.io/' # Официальный репозиторий MinIO
    chart: minio
    targetRevision: 5.4.0 # Актуальная версия на момент ответа; проверьте последнюю
    helm:
      # Используем values вместо parameters для сложных конфигураций
      values: |
        mode: distributed
        rootUser: admin
        rootPassword: password
        persistence:
          enabled: true
          storageClass: "managed-nfs-storage"
          size: 2Gi
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
        # Критически важно для работы консоли и API
        service:
          type: ClusterIP
          port: 9000
        consoleService:
          type: ClusterIP
          port: 9001
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
